name: 'Build Sailfish OS SDK container'

inputs:
  version:
    required: true

runs:
  using: 'composite'
  steps:
    -
      name: Prepare Docker meta
      id: meta
      uses: docker/metadata-action@v3
      env:
        VERSION: ${{ inputs.version }}
      with:
        images: ghcr.io/dseight/sailfishos-sdk
        tags: |
          type=ref,event=branch,suffix=-${{ env.VERSION }}
          type=ref,event=pr,suffix=-${{ env.VERSION }}
          type=semver,pattern=v{{version}}-${{ env.VERSION }}
          type=semver,pattern=v{{major}}-${{ env.VERSION }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
          VERSION=${{ inputs.version }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
