name: ci

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: ./.github/actions/build-container
        with:
          version: 3.4.0.24
      -
        uses: ./.github/actions/build-container
        with:
          version: 4.0.1.48
      -
        uses: ./.github/actions/build-container
        with:
          version: 4.1.0.24
      -
        uses: ./.github/actions/build-container
        with:
          version: 4.2.0.21
